name: Create Changesets Versioning PR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0
      - run: pnpm install
      # - run: pnpm test

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.3.0

      - name: Install Dependencies
        run: pnpm install

      - name: Create Release Pull Request
        uses: changesets/action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: pnpm version-packages
          title: "fix: version packages"
